#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Themed VOCAB_BANK entries for the 24 academies that still fall back to
arbitrary vocab. Authored in stable order so indices are deterministic:
batch 1 = indices 142.., batch 2 = next, etc.

Each entry: (academy_id, category, difficulty, {en, ipa, ar, translit,
   ex_en, ex_ar, ex_tr, syn, ant, fam, coll, tip, mistake})
"""

B1='Beginner'; I1='Intermediate'; ADV='Advanced'

# CEFR -> difficulty: A1/A2=Beginner, B1/B2=Intermediate, C1/C2=Advanced
DATA = [
# ===================== BATCH 1 =====================
('american-conversations','American Conversations',I1,
  {'en':'Catch up','ipa':'/ˌkætʃ ˈʌp/','ar':'يلحق بآخر الأحداث، يتبادل الأخبار','translit':'كاتش أب',
   'ex_en':'Let\'s grab coffee and catch up.','ex_ar':'خلّنا ناخذ قهوة ونتحدث ونشوف آخر الأخبار.','ex_tr':'ليتس قراب كوفي آند كاتش أب.',
   'syn':'reconnect, update','ant':'lose touch','fam':'catch, catches, catching up','coll':'catch up with, catch up on','tip':'Use "catch up on" for news and "catch up with" for the person.','mistake':'Saying "catch up him" instead of "catch up with him."'}),

('american-conversations','American Conversations',I1,
  {'en':'Small talk','ipa':'/ˌsmɔːl ˈtɔːk/','ar':'حديث ودي مهذّب، ثرثرة لطيفة','translit':'سمول توك',
   'ex_en':'We made small talk about the weather.','ex_ar':'دار بيننا حديث ودي عن الطقس.','ex_tr':'وي ميد سمول توك اباوت ذا ويذر.',
   'syn':'chitchat, banter','ant':'deep talk, silence','fam':'talk, talking','coll':'make small talk, engage in small talk','tip':'Small talk opens doors before serious talk.','mistake':'Saying "do small talk" instead of "make small talk."'}),

('american-conversations','American Conversations',I1,
  {'en':'Hang out','ipa':'/ˈhæŋ ˌaʊt/','ar':'يقضي وقتًا مع، يتسكّع','translit':'هانق آوت',
   'ex_en':'We hang out at the mall on weekends.','ex_ar':'نتسكع في المول آخر الأسبوع.','ex_tr':'وي هانق آوت آت ذا مول أون ويك إندز.',
   'syn':'spend time, chill','ant':'avoid, stay away','fam':'hang, hanging out','coll':'hang out with, hang out at','tip':'In past tense it becomes "hung out."','mistake':'Saying "hangouted" instead of "hung out."'}),

('american-conversations','American Conversations',I1,
  {'en':'By the way','ipa':'/baɪ ðə ˈweɪ/','ar':'على فكرة، بالمناسبة','translit':'باي ذا وي',
   'ex_en':'By the way, did you call her?','ex_ar':'على فكرة، هل اتصلت بها؟','ex_tr':'باي ذا وي، ديد يو كول هر؟',
   'syn':'incidentally, speaking of which','ant':'','fam':'way, ways','coll':'by the way, just by the way','tip':'Use it to add a side note mid-conversation.','mistake':'Writing "bytheway" as one word instead of three.'}),

('american-conversations','American Conversations',I1,
  {'en':'What\'s up','ipa':'/ˈwɒts ʌp/','ar':'ما الأخبار؟ كيف الحال؟','translit':'واتس أب',
   'ex_en':'Hey, what\'s up?','ex_ar':'أهلًا، ما الأخبار؟','ex_tr':'هي، واتس أب؟',
   'syn':'how\'s it going, what\'s new','ant':'','fam':'up','coll':'what\'s up with, what\'s up man','tip':'It\'s a greeting, not a real question about problems.','mistake':'Answering with a long story instead of "not much, you?"'}),

('speaking-studio','Speaking Studio',I1,
  {'en':'Fluency','ipa':'/ˈfluːənsi/','ar':'طلاقة، سلاسة في الكلام','translit':'فلونسي',
   'ex_en':'Her fluency in English improved fast.','ex_ar':'تحسّنت طلاقتها في الإنجليزية بسرعة.','ex_tr':'هر فلونسي إن إنجلش امبروفد فاست.',
   'syn':'smoothness, flow','ant':'hesitation, stumbling','fam':'fluent, fluently','coll':'speak with fluency, build fluency','tip':'Fluency is about flow, not perfect grammar.','mistake':'Stopping at every small mistake kills fluency.'}),

('speaking-studio','Speaking Studio',I1,
  {'en':'Pronunciation','ipa':'/prəˌnʌnsiˈeɪʃən/','ar':'النطق، طريقة لفظ الكلمات','translit':'برنانسييهيشِن',
   'ex_en':'His pronunciation is very clear.','ex_ar':'نطقه واضح جدًا.','ex_tr':'هيز برنانسييهيشِن إز فيري كلير.',
   'syn':'articulation, diction','ant':'mispronunciation','fam':'pronounce, pronounced','coll':'clear pronunciation, improve pronunciation','tip':'The word itself has no "o" after the "n."','mistake':'Spelling it "pronounciation."'}),

('speaking-studio','Speaking Studio',I1,
  {'en':'Pause','ipa':'/pɔːz/','ar':'وقفة، توقف قصير','translit':'بوز',
   'ex_en':'Take a short pause to breathe.','ex_ar':'خذ وقفة قصيرة لتتنفس.','ex_tr':'تيك ا شورت بوز تو بريث.',
   'syn':'break, stop','ant':'continue, rush','fam':'pause, paused, pausing','coll':'take a pause, pause for effect','tip':'A pause adds power to your words.','mistake':'Filling every pause with "um" and "uh."'}),

('speaking-studio','Speaking Studio',I1,
  {'en':'Hesitate','ipa':'/ˈhezɪteɪt/','ar':'يتردد، يتوقف غير متأكد','translit':'هزيتيت',
   'ex_en':'Don\'t hesitate to ask questions.','ex_ar':'لا تتردد في طرح الأسئلة.','ex_tr':'دونت هزيتيت تو أسك كويستشنز.',
   'syn':'waver, falter','ant':'decide, act','fam':'hesitation, hesitantly','coll':'hesitate to, hesitate before','tip':'Confidence grows when you speak anyway.','mistake':'Saying "hestitate" and dropping a syllable.'}),

('speaking-studio','Speaking Studio',I1,
  {'en':'Express','ipa':'/ɪkˈsprɛs/','ar':'يعبّر، يوضّح','translit':'إكسبريس',
   'ex_en':'Express your idea simply.','ex_ar':'عبّر عن فكرتك ببساطة.','ex_tr':'إكسبريس يور آيديا سيمبلي.',
   'syn':'convey, state','ant':'hide, suppress','fam':'expression, expressive','coll':'express yourself, express an opinion','tip':'Simple words express ideas best.','mistake':'Saying "I am express" instead of "I express."'}),

('american-accent-lab','American Accent Lab',I1,
  {'en':'Vowel','ipa':'/ˈvaʊəl/','ar':'حرف متحرك (مثل a, e, i)','translit':'فاويل',
   'ex_en':'The word "beat" has a long vowel.','ex_ar':'كلمة "beat" بها حرف متحرك طويل.','ex_tr':'ذا وورد بيت هاز ا لونق فاويل.',
   'syn':'vowel sound','ant':'consonant','fam':'vowel, vowelled','coll':'long vowel, short vowel','tip':'American vowels are often longer when stressed.','mistake':'Confusing short "i" with long "ee."'}),

('american-accent-lab','American Accent Lab',I1,
  {'en':'Consonant','ipa':'/ˈkɒnsənənt/','ar':'حرف ساكن (مثل b, c, d)','translit':'كونسوننت',
   'ex_en':'"B" is a consonant letter.','ex_ar':'حرف "B" حرف ساكن.','ex_tr':'بي إز ا كونسوننت ليتر.',
   'syn':'consonant sound','ant':'vowel','fam':'consonant, consonantal','coll':'voiced consonant, double consonant','tip':'Consonants carry rhythm, vowels carry melody.','mistake':'Pronouncing silent consonants like the "k" in "knee."'}),

('american-accent-lab','American Accent Lab',I1,
  {'en':'Stress','ipa':'/strɛs/','ar':'النبر، التشديد على مقطع','translit':'سترِس',
   'ex_en':'Stress the second syllable.','ex_ar':'شدّد على المقطع الثاني.','ex_tr':'سترِس ذا سيكون سيلابَل.',
   'syn':'emphasis, accent','ant':'unstress','fam':'stress, stressed, stressing','coll':'word stress, stress a syllable','tip':'Stress changes meaning: REcord vs reCORD.','mistake':'Stressing every syllable equally.'}),

('american-accent-lab','American Accent Lab',I1,
  {'en':'Syllable','ipa':'/ˈsɪləbəl/','ar':'مقطع لفظي','translit':'سيلابَل',
   'ex_en':'"Water" has two syllables.','ex_ar':'كلمة "water" تتكون من مقطعين.','ex_tr':'واتر هاز تو سيلابَلز.',
   'syn':'beat, unit of sound','ant':'','fam':'syllable, syllabic','coll':'stressed syllable, count syllables','tip':'Clap the word to count its syllables.','mistake':'Saying "sy-lla-ble" as four parts; it is three.'}),

('american-accent-lab','American Accent Lab',I1,
  {'en':'Intonation','ipa':'/ˌɪntəˈneɪʃən/','ar':'التنغيم، نبرة الجملة','translit':'إنتونيهيشِن',
   'ex_en':'Rising intonation marks a question.','ex_ar':'التنغيم الصاعد يدل على سؤال.','ex_tr':'رايزينق إنتونيهيشِن ماركس ا كويستشن.',
   'syn':'pitch, melody','ant':'monotone','fam':'intonate, intonation','coll':'rising intonation, falling intonation','tip':'Your voice rises for questions, falls for statements.','mistake':'Speaking in a flat, robot-like tone.'}),

('vocabulary-vault','Vocabulary Vault',I1,
  {'en':'Synonym','ipa':'/ˈsɪnənɪm/','ar':'مرادف، كلمة بنفس المعنى','translit':'سينونيم',
   'ex_en':'"Happy" is a synonym of "glad."','ex_ar':'كلمة "happy" مرادف لكلمة "glad."','ex_tr':'هابي إز ا سينونيم أوف گلاد.',
   'syn':'equivalent, match','ant':'antonym','fam':'synonym, synonymous','coll':'exact synonym, near synonym','tip':'Learn synonyms to avoid repeating words.','mistake':'Thinking synonyms are always interchangeable in tone.'}),

('vocabulary-vault','Vocabulary Vault',I1,
  {'en':'Antonym','ipa':'/ˈæntənɪm/','ar':'ضد، كلمة بمعنى معاكس','translit':'أنتونيم',
   'ex_en':'"Hot" is an antonym of "cold."','ex_ar':'كلمة "hot" ضد لكلمة "cold."','ex_tr':'هوت إز أن أنتونيم أوف كولد.',
   'syn':'opposite','ant':'synonym','fam':'antonym, antonymous','coll':'exact antonym','tip':'Pair new words with their antonyms to remember both.','mistake':'Confusing antonym with "anonymous."'}),

('vocabulary-vault','Vocabulary Vault',I1,
  {'en':'Context','ipa':'/ˈkɒntɛkst/','ar':'السياق، القرينة','translit':'كونتيكست',
   'ex_en':'Guess the word from its context.','ex_ar':'خمّن الكلمة من سياقها.','ex_tr':'گيس ذا وورد فروم ايتس كونتيكست.',
   'syn':'setting, situation','ant':'','fam':'context, contextual','coll':'in context, out of context','tip':'Context tells you which meaning fits.','mistake':'Quoting a word "out of context" changes its sense.'}),

('vocabulary-vault','Vocabulary Vault',I1,
  {'en':'Definition','ipa':'/ˌdɛfɪˈnɪʃən/','ar':'تعريف، معنى الكلمة','translit':'ديفينيشِن',
   'ex_en':'Read the definition carefully.','ex_ar':'اقرأ التعريف بعناية.','ex_tr':'ريد ذا ديفينيشِن كيرفلي.',
   'syn':'meaning, explanation','ant':'ambiguity','fam':'define, defining','coll':'clear definition, by definition','tip':'A good definition uses simple words.','mistake':'Copying a definition without understanding it.'}),

('vocabulary-vault','Vocabulary Vault',I1,
  {'en':'Prefix','ipa':'/ˈpriːfɪks/','ar':'بادئة، جزء يضاف أول الكلمة','translit':'بريفيكس',
   'ex_en':'"Un-" is a prefix in "unhappy."','ex_ar':'"Un-" بادئة في "unhappy."','ex_tr':'أن إز ا بريفيكس إن أن هابي.',
   'syn':'starter','ant':'suffix','fam':'prefix, prefixed','coll':'add a prefix, common prefix','tip':'Prefixes like "un-" often reverse meaning.','mistake':'Confusing prefix with suffix.'}),

('grammar-academy','Grammar Academy',I1,
  {'en':'Noun','ipa':'/naʊn/','ar':'اسم، كلمة تدل على شخص أو شيء','translit':'ناون',
   'ex_en':'"Book" is a noun.','ex_ar':'"Book" اسم.','ex_tr':'بوك إز ا ناون.',
   'syn':'naming word','ant':'','fam':'noun','coll':'common noun, proper noun','tip':'Proper nouns like "Riyadh" are capitalized.','mistake':'Forgetting to capitalize proper nouns.'}),

('grammar-academy','Grammar Academy',I1,
  {'en':'Verb','ipa':'/vɜːb/','ar':'فعل، كلمة تدل على حدث','translit':'فِرب',
   'ex_en':'"Run" is an action verb.','ex_ar':'"Run" فعل حركة.','ex_tr':'رَن إز أن أكشن فِرب.',
   'syn':'action word','ant':'','fam':'verb, verbal','coll':'main verb, helping verb','tip':'Every sentence needs at least one verb.','mistake':'Writing a sentence with no verb.'}),

('grammar-academy','Grammar Academy',I1,
  {'en':'Adjective','ipa':'/ˈædʒɪktɪv/','ar':'نعت، صفة','translit':'أدجيكتيف',
   'ex_en':'"Tall" is an adjective.','ex_ar':'"Tall" صفة.','ex_tr':'تول إز أن أدجيكتيف.',
   'syn':'describing word','ant':'','fam':'adjective','coll':'comparative adjective, descriptive adjective','tip':'Adjectives come before nouns: "a tall man."','mistake':'Saying "a man tall" instead of "a tall man."'}),

('grammar-academy','Grammar Academy',I1,
  {'en':'Tense','ipa':'/tɛns/','ar':'زمن الفعل (ماضي/مضارع)','translit':'تينس',
   'ex_en':'Use the past tense for finished actions.','ex_ar':'استخدم زمن الماضي للأفعال المنتهية.','ex_tr':'يوز ذا باست تينس فور فينيشد أكشنز.',
   'syn':'verb form, time','ant':'','fam':'tense, tenses','coll':'past tense, present tense','tip':'Tense shows when an action happens.','mistake':'Mixing "went" and "go" in the same time frame.'}),

('grammar-academy','Grammar Academy',I1,
  {'en':'Subject','ipa':'/ˈsʌbdʒɪkt/','ar':'الفاعل، من يقوم بالفعل','translit':'سَبجيكت',
   'ex_en':'The subject comes before the verb.','ex_ar':'الفاعل يأتي قبل الفعل.','ex_tr':'ذا سَبجيكت كامز بي فور ذا فِرب.',
   'syn':'doer, agent','ant':'object','fam':'subject, subjective','coll':'subject of the sentence','tip':'Ask "who?" to find the subject.','mistake':'Confusing subject with object.'}),

('listening-lounge','Listening Lounge',I1,
  {'en':'Accent','ipa':'/ˈæksənt/','ar':'لهجة، طريقة نطق','translit':'أكسينت',
   'ex_en':'She has a strong American accent.','ex_ar':'لديها لهجة أمريكية واضحة.','ex_tr':'شي هاز ا سترونق أمريكان أكسينت.',
   'syn':'dialect, pronunciation','ant':'','fam':'accent, accented','coll':'strong accent, soft accent','tip':'Accents are normal; clarity matters more.','mistake':'Thinking an accent means bad English.'}),

('listening-lounge','Listening Lounge',I1,
  {'en':'Audio','ipa':'/ˈɔːdi.oʊ/','ar':'صوت مسجل','translit':'أوديو',
   'ex_en':'The audio is too quiet.','ex_ar':'الصوت المسجّل منخفض جدًا.','ex_tr':'ذا أوديو إز تو كوايت.',
   'syn':'sound, recording','ant':'silence','fam':'audio, audiovisual','coll':'audio clip, play the audio','tip':'Good audio helps you catch every word.','mistake':'Saying "the audios" as a plural noun.'}),

('listening-lounge','Listening Lounge',I1,
  {'en':'Replay','ipa':'/ˌriːˈpleɪ/','ar':'إعادة، يشغّل مرة أخرى','translit':'ري بلاي',
   'ex_en':'Replay the part you missed.','ex_ar':'أعد تشغيل الجزء الذي فاتك.','ex_tr':'ري بلاي ذا بارت يو ميست.',
   'syn':'play again, repeat','ant':'skip','fam':'replay, replayed','coll':'replay a clip, hit replay','tip':'Replay hard parts until they feel easy.','mistake':'Moving on without replaying unclear parts.'}),

('listening-lounge','Listening Lounge',I1,
  {'en':'Mumble','ipa':'/ˈmʌmbəl/','ar':'يهمس، يتكلم بغير وضوح','translit':'مَمبَل',
   'ex_en':'Don\'t mumble; speak clearly.','ex_ar':'لا تهمس؛ تحدث بوضوح.','ex_tr':'دونت مَمبَل؛ سبيك كليرلي.',
   'syn':'mutter, whisper','ant':'enunciate, shout','fam':'mumble, mumbled','coll':'mumble words, mumble to yourself','tip':'Open your mouth more to avoid mumbling.','mistake':'Mumbling from nervousness and losing the listener.'}),

('listening-lounge','Listening Lounge',I1,
  {'en':'Volume','ipa':'/ˈvɒljuːm/','ar':'مستوى الصوت، ارتفاعه','translit':'فوليوم',
   'ex_en':'Turn up the volume.','ex_ar':'ارفع مستوى الصوت.','ex_tr':'تيرن أب ذا فوليوم.',
   'syn':'loudness, level','ant':'mute','fam':'volume','coll':'turn up the volume, lower the volume','tip':'A clear volume helps you catch detail.','mistake':'Setting volume too high and missing soft sounds.'}),
# ===================== BATCH 2 =====================
('reading-corner','Reading Corner',I1,
  {'en':'Skim','ipa':'/skɪm/','ar':'يقرأ بسرعة، يتصفّح','translit':'سكيم',
   'ex_en':'Skim the article for the main idea.','ex_ar':'تصفّح المقال بسرعة لتأخذ الفكرة العامة.','ex_tr':'سكيم ذا أرتيكل فور ذا مين آيديا.',
   'syn':'browse, glance','ant':'study, read closely','fam':'skim, skimmed, skimming','coll':'skim through, skim a text','tip':'Skimming is for the gist, not details.','mistake':'Trying to understand every word while skimming.'}),
('reading-corner','Reading Corner',I1,
  {'en':'Scan','ipa':'/skæn/','ar':'يبحث سريعًا عن معلومة','translit':'سكان',
   'ex_en':'Scan the page for the date.','ex_ar':'ابحث في الصفحة عن التاريخ بسرعة.','ex_tr':'سكان ذا بايج فور ذا ديت.',
   'syn':'search, comb','ant':'browse','fam':'scan, scanned, scanning','coll':'scan for, scan a list','tip':'Scanning looks for one specific thing.','mistake':'Confusing scan (search) with skim (overview).'}),
('reading-corner','Reading Corner',I1,
  {'en':'Passage','ipa':'/ˈpæsɪdʒ/','ar':'مقطع، فقرة نصية','translit':'باسيج',
   'ex_en':'Read the first passage carefully.','ex_ar':'اقرأ المقطع الأول بعناية.','ex_tr':'ريد ذا فيرست باسيج كيرفلي.',
   'syn':'text, excerpt','ant':'','fam':'passage, passages','coll':'reading passage, short passage','tip':'A passage is a short piece of writing.','mistake':'Pronouncing it like "massage."'}),
('reading-corner','Reading Corner',I1,
  {'en':'Headline','ipa':'/ˈhɛdlaɪn/','ar':'عنوان رئيسي','translit':'هيدلاين',
   'ex_en':'The headline caught my eye.','ex_ar':'لفت العنوان الرئيسي انتباهي.','ex_tr':'ذا هيدلاين كاوت ماي آي.',
   'syn':'title, header','ant':'footer','fam':'headline, headlined','coll':'front-page headline, write a headline','tip':'Headlines summarize the whole story.','mistake':'Writing a headline that is too long.'}),
('reading-corner','Reading Corner',I1,
  {'en':'Summarize','ipa':'/ˈsʌməraɪz/','ar':'يلخّص','translit':'سَمريايز',
   'ex_en':'Summarize the story in one sentence.','ex_ar':'لخّص القصة في جملة واحدة.','ex_tr':'سَمريايز ذا ستوري إن وان سينتينس.',
   'syn':'condense, outline','ant':'expand, detail','fam':'summary, summarizing','coll':'summarize in, briefly summarize','tip':'A summary keeps only the main points.','mistake':'Adding new ideas instead of summarizing.'}),
('writing-workshop','Writing Workshop',ADV,
  {'en':'Essay','ipa':'/ˈɛseɪ/','ar':'مقال، موضوع','translit':'إسّاي',
   'ex_en':'Write a short essay on the topic.','ex_ar':'اكتب مقالًا قصيرًا عن الموضوع.','ex_tr':'رايت ا شورت إسّاي أون ذا تابيك.',
   'syn':'paper, composition','ant':'','fam':'essay, essayist','coll':'write an essay, essay question','tip':'An essay has intro, body, conclusion.','mistake':'Skipping the conclusion of an essay.'}),
('writing-workshop','Writing Workshop',ADV,
  {'en':'Thesis','ipa':'/ˈθiːsɪs/','ar':'أطروحة، فكرة رئيسية','translit':'ثيسيس',
   'ex_en':'State your thesis early.','ex_ar':'اذكر فكرتك الرئيسية مبكرًا.','ex_tr':'ستيت يور ثيسيس إرلي.',
   'syn':'main idea, argument','ant':'','fam':'thesis','coll':'thesis statement, defend a thesis','tip':'One sentence that holds the whole essay.','mistake':'Writing a thesis that is too vague.'}),
('writing-workshop','Writing Workshop',ADV,
  {'en':'Draft','ipa':'/drɑːft/','ar':'مسودة، نسخة أولية','translit':'درافت',
   'ex_en':'This is just a first draft.','ex_ar':'هذه مجرد مسودة أولى.','ex_tr':'ذيس إز جاست ا فيرست درافت.',
   'syn':'outline, sketch','ant':'final version','fam':'draft, drafted, drafting','coll':'rough draft, draft an essay','tip':'A draft is meant to be improved.','mistake':'Treating the first draft as the final version.'}),
('writing-workshop','Writing Workshop',ADV,
  {'en':'Revise','ipa':'/rɪˈvaɪz/','ar':'يراجع ويعدّل','translit':'ريفايز',
   'ex_en':'Revise your draft for clarity.','ex_ar':'راجع مسودتك لتكون أوضح.','ex_tr':'ريفايز يور درافت فور كليريتي.',
   'syn':'edit, rewrite','ant':'keep, leave','fam':'revise, revision','coll':'revise for, revise a draft','tip':'Revise for ideas, then edit for grammar.','mistake':'Revising and editing at the same time.'}),
('writing-workshop','Writing Workshop',ADV,
  {'en':'Paragraph','ipa':'/ˈpærəɡræf/','ar':'فقرة','translit':'باراگراف',
   'ex_en':'Each paragraph needs one main idea.','ex_ar':'كل فقرة تحتاج فكرة رئيسية واحدة.','ex_tr':'إتش باراگراف نيدز وان مين آيديا.',
   'syn':'section, stanza','ant':'','fam':'paragraph','coll':'opening paragraph, topic sentence','tip':'Start a paragraph with its main idea.','mistake':'Putting several ideas in one paragraph.'}),
('coffee-shop-english','Coffee Shop English',B1,
  {'en':'Espresso','ipa':'/ɛˈsprɛsoʊ/','ar':'إسبريسو، قهوة مركّزة','translit':'إسبريسو',
   'ex_en':'I\'ll have an espresso, please.','ex_ar':'أريد إسبريسو من فضلك.','ex_tr':'ايل هاف أن إسبريسو، بليز.',
   'syn':'short black','ant':'','fam':'espresso','coll':'double espresso, espresso shot','tip':'Espresso is the base for many drinks.','mistake':'Pronouncing it as "expresso."'}),
('coffee-shop-english','Coffee Shop English',B1,
  {'en':'Latte','ipa':'/ˈlɑːteɪ/','ar':'لاتيه، قهوة بالحليب','translit':'لاتيه',
   'ex_en':'A latte has more milk than coffee.','ex_ar':'اللاتيه فيه حليب أكثر من القهوة.','ex_tr':'ا لاتيه هاز مور ميلك ذان كوفي.',
   'syn':'cafe latte','ant':'','fam':'latte','coll':'order a latte, iced latte','tip':'Stress the second part: la-TAY.','mistake':'Saying "lat-ee" instead of "la-TAY."'}),
('coffee-shop-english','Coffee Shop English',B1,
  {'en':'Barista','ipa':'/bəˈriːstə/','ar':'باريستا، صانع القهوة','translit':'باريستا',
   'ex_en':'The barista made a nice latte art.','ex_ar':'الباريستا صمّم رسمة لاتيه جميلة.','ex_tr':'ذا باريستا ميد ا نايس لاتيه آرت.',
   'syn':'coffee maker','ant':'','fam':'barista','coll':'ask the barista, skilled barista','tip':'A barista prepares and serves coffee.','mistake':'Pronouncing it "bar-ista" with wrong stress.'}),
('coffee-shop-english','Coffee Shop English',B1,
  {'en':'To Go','ipa':'/tu ɡoʊ/','ar':'للسفري، يُؤخذ معك','translit':'تو قو',
   'ex_en':'Coffee to go, please.','ex_ar':'قهوة للسفري من فضلك.','ex_tr':'كوفي تو قو، بليز.',
   'syn':'takeaway, takeout','ant':'for here, dine in','fam':'go','coll':'to go order, for here or to go','tip':'"To go" means take it with you.','mistake':'Saying "to go away" instead of "to go."'}),
('coffee-shop-english','Coffee Shop English',B1,
  {'en':'Decaf','ipa':'/ˈdiːkæf/','ar':'قهوة منزوعة الكافيين','translit':'ديكاف',
   'ex_en':'I\'ll have decaf, please.','ex_ar':'أريد قهوة منزوعة الكافيين من فضلك.','ex_tr':'ايل هاف ديكاف، بليز.',
   'syn':'caffeine-free','ant':'regular, caffeinated','fam':'decaf, decaffeinated','coll':'order decaf, decaf coffee','tip':'Decaf is short for decaffeinated.','mistake':'Thinking decaf has zero caffeine; it has a little.'}),
('american-slang','American Slang',ADV,
  {'en':'Cool','ipa':'/kuːl/','ar':'رائع، ممتاز','translit':'كول',
   'ex_en':'That movie was cool!','ex_ar':'ذاك الفيلم كان رائعًا!','ex_tr':'ذا موفي واز كول!',
   'syn':'awesome, great','ant':'lame, uncool','fam':'cool, cooler','coll':'look cool, pretty cool','tip':'"Cool" means good or okay in slang.','mistake':'Using "cool" only for temperature.'}),
('american-slang','American Slang',ADV,
  {'en':'Buck','ipa':'/bʌk/','ar':'دولار','translit':'بَك',
   'ex_en':'It costs five bucks.','ex_ar':'يكلّف خمسة دولارات.','ex_tr':'إت كوستس فايڤ بَكس.',
   'syn':'dollar, bill','ant':'','fam':'buck, bucks','coll':'a few bucks, make a buck','tip':'"Buck" is slang for one dollar.','mistake':'Thinking it only means a male deer.'}),
('american-slang','American Slang',ADV,
  {'en':'Hang Out','ipa':'/ˈhæŋ ˌaʊt/','ar':'يقضي وقتًا مع، يتسكّع','translit':'هانق آوت',
   'ex_en':'Let\'s hang out this weekend.','ex_ar':'خلّنا نتسكع نهاية الأسبوع.','ex_tr':'ليتس هانق آوت ذيس ويك إند.',
   'syn':'chill, spend time','ant':'avoid','fam':'hang, hanging out','coll':'hang out with, hang out at','tip':'Past tense is "hung out."','mistake':'Saying "hangouted" instead of "hung out."'}),
('american-slang','American Slang',ADV,
  {'en':'Rip Off','ipa':'/rɪp ɒf/','ar':'يغش، يستغل، سعر مبالغ فيه','translit':'ريب أوف',
   'ex_en':'That price is a rip-off.','ex_ar':'ذاك السعر استغلال.','ex_tr':'ذا برايس إز ا ريب أوف.',
   'syn':'overcharge, scam','ant':'bargain, fair deal','fam':'rip, ripped off','coll':'rip someone off, a rip-off','tip':'"Rip off" can be a verb or a noun.','mistake':'Saying "rip me off" when you mean "ripped me off."'}),
('american-slang','American Slang',ADV,
  {'en':'Beat','ipa':'/biːt/','ar':'منهك، متعب جدًا','translit':'بيت',
   'ex_en':'I\'m beat after work.','ex_ar':'أنا منهك بعد العمل.','ex_tr':'ايم بيت أفتار وورك.',
   'syn':'exhausted, tired','ant':'energetic, fresh','fam':'beat, beaten','coll':'feel beat, look beat','tip':'In slang "beat" means very tired.','mistake':'Confusing it with "beat" (to hit).'}),
('idioms-library','Idioms Library',ADV,
  {'en':'Break a leg','ipa':'/breɪk ə lɛɡ/','ar':'حظًا سعيدًا','translit':'بريك ا لَق',
   'ex_en':'Break a leg tonight!','ex_ar':'حظًا سعيدًا الليلة!','ex_tr':'بريك ا لَق تونايت!',
   'syn':'good luck','ant':'bad luck','fam':'break, broke','coll':'say break a leg, tell someone break a leg','tip':'It means good luck, especially on stage.','mistake':'Taking "break a leg" literally.'}),
('idioms-library','Idioms Library',ADV,
  {'en':'Piece of cake','ipa':'/piːs əv ˈkeɪk/','ar':'أمر سهل جدًا','translit':'بيس أوف كيك',
   'ex_en':'The test was a piece of cake.','ex_ar':'كان الاختبار سهلًا جدًا.','ex_tr':'ذا تست واز ا بيس أوف كيك.',
   'syn':'very easy, a breeze','ant':'very hard, tough','fam':'cake','coll':'be a piece of cake','tip':'It describes something very easy.','mistake':'Thinking it is about actual food.'}),
('idioms-library','Idioms Library',ADV,
  {'en':'Hit the books','ipa':'/hɪt ðə bʊks/','ar':'يذاكر بجد','translit':'هيت ذا بوكز',
   'ex_en':'I need to hit the books tonight.','ex_ar':'يجب أن أذاكر بجد الليلة.','ex_tr':'اي نيد تو هيت ذا بوكز تونايت.',
   'syn':'study hard, cram','ant':'slack off','fam':'hit, books','coll':'hit the books for','tip':'It means to study seriously.','mistake':'Hitting actual books.'}),
('idioms-library','Idioms Library',ADV,
  {'en':'Under the weather','ipa':'/ˈʌndər ðə ˈwɛðər/','ar':'متوعّك، غير بصحة جيدة','translit':'أندر ذا ويذر',
   'ex_en':'I feel under the weather today.','ex_ar':'أشعر بالتوعك اليوم.','ex_tr':'اي فيل أندر ذا ويذر توداي.',
   'syn':'a bit sick, unwell','ant':'healthy, fit','fam':'weather','coll':'feel under the weather','tip':'It means feeling slightly ill.','mistake':'Thinking it is about the climate.'}),
('idioms-library','Idioms Library',ADV,
  {'en':'Once in a blue moon','ipa':'/wʌns ɪn ə bluː muːn/','ar':'نادرًا جدًا','translit':'ونس إن ا بلو مون',
   'ex_en':'We meet once in a blue moon.','ex_ar':'نلتقي نادرًا جدًا.','ex_tr':'وي ميت ونس إن ا بلو مون.',
   'syn':'rarely, seldom','ant':'often, frequently','fam':'moon','coll':'happen once in a blue moon','tip':'It means almost never.','mistake':'Using it for something that happens often.'}),
('phrasal-verbs-lab','Phrasal Verbs Lab',ADV,
  {'en':'Give up','ipa':'/ɡɪv ʌp/','ar':'يستسلم، يتوقف عن','translit':'گيف أب',
   'ex_en':'Don\'t give up on your dreams.','ex_ar':'لا تتخلَّ عن أحلامك.','ex_tr':'دونت گيف أب أون يور دريمز.',
   'syn':'quit, surrender','ant':'keep going, persevere','fam':'give, gave up','coll':'give up on, give up trying','tip':'"Give up" means to stop trying.','mistake':'Saying "give up to" instead of "give up on."'}),
('phrasal-verbs-lab','Phrasal Verbs Lab',ADV,
  {'en':'Look forward to','ipa':'/lʊk ˈfɔːrwərd tu/','ar':'يتطلّع إلى، ينتظر بشغف','translit':'لوك فوروورد تو',
   'ex_en':'I look forward to the weekend.','ex_ar':'أتطلّع إلى نهاية الأسبوع.','ex_tr':'اي لوك فوروورد تو ذا ويك إند.',
   'syn':'anticipate, await','ant':'dread','fam':'look, looked forward','coll':'look forward to doing, look forward to seeing','tip':'Follow it with a noun or -ing verb.','mistake':'Saying "look forward to see" instead of "to seeing."'}),
('phrasal-verbs-lab','Phrasal Verbs Lab',ADV,
  {'en':'Turn out','ipa':'/tɜːrn aʊt/','ar':'ينتج، يتضح','translit':'تيرن آوت',
   'ex_en':'It turned out fine.','ex_ar':'اتضح أنه بخير.','ex_tr':'إت تيرند آوت فاين.',
   'syn':'result, end up','ant':'','fam':'turn, turned out','coll':'turn out well, turn out that','tip':'It shows how a situation ends.','mistake':'Confusing it with "turn off."'}),
('phrasal-verbs-lab','Phrasal Verbs Lab',ADV,
  {'en':'Get along','ipa':'/ɡɛt əˈlɒŋ/','ar':'يتفق مع، يتوافق','translit':'گيت ألونق',
   'ex_en':'They get along well.','ex_ar':'هما يتفقان جيدًا.','ex_tr':'ذاي گيت ألونق ويل.',
   'syn':'get on, agree','ant':'clash, fight','fam':'get, got along','coll':'get along with, get along well','tip':'Use "get along with" for a person.','mistake':'Saying "get along to" instead of "get along with."'}),
('phrasal-verbs-lab','Phrasal Verbs Lab',ADV,
  {'en':'Figure out','ipa':'/ˈfɪɡjər aʊt/','ar':'يفهم، يحلّ','translit':'فيغير آوت',
   'ex_en':'I can\'t figure out the answer.','ex_ar':'لا أستطيع أن أفهم الإجابة.','ex_tr':'اي كانت فيغير آوت ذا أنسر.',
   'syn':'solve, work out','ant':'be confused by','fam':'figure, figured out','coll':'figure out how, figure out what','tip':'It means to understand or solve.','mistake':'Saying "figure out of" instead of "figure out."'}),
# ===================== BATCH 3 =====================
('tv-series-english','TV Series English',ADV,
  {'en':'Episode','ipa':'/ˈɛpɪsoʊd/','ar':'حلقة (من مسلسل)','translit':'إبّيسود',
   'ex_en':'This episode was exciting.','ex_ar':'كانت هذه الحلقة مثيرة.','ex_tr':'ذيس إبّيسود واز إكسايتينق.',
   'syn':'instalment, show','ant':'','fam':'episode, episodic','coll':'watch an episode, new episode','tip':'A season is made of several episodes.','mistake':'Pronouncing it "eppi-sode."'}),
('tv-series-english','TV Series English',ADV,
  {'en':'Season','ipa':'/ˈsiːzən/','ar':'موسم (من مسلسل)','translit':'سيزِن',
   'ex_en':'Season two is better.','ex_ar':'الموسم الثاني أفضل.','ex_tr':'سيزِن تو إز بيتر.',
   'syn':'series run','ant':'','fam':'season, seasons','coll':'new season, finale season','tip':'A season groups many episodes.','mistake':'Confusing TV season with weather season.'}),
('tv-series-english','TV Series English',ADV,
  {'en':'Spoiler','ipa':'/ˈspɔɪlər/','ar':'كاشف للأحداث، حرق للقصة','translit':'سبويلر',
   'ex_en':'No spoilers, please!','ex_ar':'لا حرق للأحداث من فضلك!','ex_tr':'نو سبويلرز، بليز!',
   'syn':'reveal, giveaway','ant':'teaser','fam':'spoil, spoilers','coll':'spoiler alert, post spoilers','tip':'A spoiler reveals what happens later.','mistake':'Posting spoilers without a warning.'}),
('tv-series-english','TV Series English',ADV,
  {'en':'Binge','ipa':'/bɪndʒ/','ar':'يشاهد حلقات متتالية','translit':'بينج',
   'ex_en':'We binged the whole season.','ex_ar':'شاهدنا الموسم كاملًا دفعة واحدة.','ex_tr':'وي بينجد ذا هول سيزن.',
   'syn':'binge-watch, devour','ant':'pace out','fam':'binge, binged','coll':'binge watch, binge on','tip':'To binge is to watch many at once.','mistake':'Saying "binge on it" when you mean "binge-watch."'}),
('tv-series-english','TV Series English',ADV,
  {'en':'Streaming','ipa':'/ˈstriːmɪŋ/','ar':'بث، مشاهدة عبر الإنترنت','translit':'ستريمينق',
   'ex_en':'Is the show streaming?','ex_ar':'هل المسلسل متاح للمشاهدة؟','ex_tr':'إز ذا شو ستريمينق؟',
   'syn':'online viewing','ant':'download, broadcast','fam':'stream, streamed','coll':'streaming service, live streaming','tip':'Streaming means watching online, live.','mistake':'Confusing streaming with downloading.'}),
('music-english','Music English',I1,
  {'en':'Lyrics','ipa':'/ˈlɪrɪks/','ar':'كلمات أغنية','translit':'ليريكس',
   'ex_en':'I love the lyrics.','ex_ar':'أحب كلمات الأغنية.','ex_tr':'اي لاف ذا ليريكس.',
   'syn':'words, lines','ant':'melody, tune','fam':'lyric, lyrical','coll':'write lyrics, sing the lyrics','tip':'Lyrics are the words of a song.','mistake':'Calling them "the words" instead of "lyrics."'}),
('music-english','Music English',I1,
  {'en':'Chorus','ipa':'/ˈkɔːrəs/','ar':'المقطع المتكرر، اللازمة','translit':'كورَس',
   'ex_en':'Sing the chorus with me.','ex_ar':'غنِّ المقطع المتكرر معي.','ex_tr':'سينق ذا كورَس ويذ مي.',
   'syn':'refrain, hook','ant':'verse','fam':'chorus, choruses','coll':'sing the chorus, catchy chorus','tip':'The chorus repeats throughout a song.','mistake':'Confusing chorus with verse.'}),
('music-english','Music English',I1,
  {'en':'Verse','ipa':'/vɜːrs/','ar':'المقطع (في الأغنية)','translit':'فِرس',
   'ex_en':'The first verse is slow.','ex_ar':'المقطع الأول بطيء.','ex_tr':'ذا فيرست فِرس إز سلوه.',
   'syn':'stanza, section','ant':'chorus','fam':'verse, versed','coll':'first verse, write a verse','tip':'A verse tells the story between choruses.','mistake':'Mixing up verse and chorus.'}),
('music-english','Music English',I1,
  {'en':'Melody','ipa':'/ˈmɛlədi/','ar':'لحن','translit':'ميلودي',
   'ex_en':'The melody is catchy.','ex_ar':'اللحن ممتع.','ex_tr':'ذا ميلودي إز كاتشي.',
   'syn':'tune, air','ant':'noise, dissonance','fam':'melody, melodic','coll':'hum a melody, simple melody','tip':'A melody is the main tune of a song.','mistake':'Calling it "the music" instead of "the melody."'}),
('music-english','Music English',I1,
  {'en':'Beat','ipa':'/biːt/','ar':'إيقاع، نبض','translit':'بيت',
   'ex_en':'Tap your foot to the beat.','ex_ar':'نقر بقدمك مع الإيقاع.','ex_tr':'تاب يور فوت تو ذا بيت.',
   'syn':'rhythm, pulse','ant':'silence','fam':'beat, beats','coll':'keep the beat, strong beat','tip':'The beat is the steady pulse of a song.','mistake':'Confusing beat with melody.'}),
('english-mastery','English Mastery',ADV,
  {'en':'Nuance','ipa':'/ˈnjuːɑːns/','ar':'فرق دقيق، ظلّ معنى','translit':'نيوانس',
   'ex_en':'Notice the nuance in tone.','ex_ar':'لاحظ الفرق الدقيق في النبرة.','ex_tr':'نوتيس ذا نيوانس إن تون.',
   'syn':'shade, subtlety','ant':'obviousness','fam':'nuance, nuanced','coll':'subtle nuance, capture a nuance','tip':'A nuance is a small, subtle difference.','mistake':'Treating synonyms as having no nuance.'}),
('english-mastery','English Mastery',ADV,
  {'en':'Articulate','ipa':'/ɑːrˈtɪkjuleɪt/','ar':'يعبّر بوضوح','translit':'أرتيكيوليت',
   'ex_en':'She articulates her ideas well.','ex_ar':'تعبّر عن أفكارها بوضوح.','ex_tr':'شي أرتيكيوليتس هر آيدياز ويل.',
   'syn':'express, voice','ant':'mumble, garble','fam':'articulate, articulation','coll':'articulate clearly, articulate a thought','tip':'To articulate is to speak clearly.','mistake':'Stressing the wrong syllable: ar-TIC-u-late.'}),
('english-mastery','English Mastery',ADV,
  {'en':'Eloquence','ipa':'/ˈɛləkwəns/','ar':'بلاغة، فصاحة','translit':'إلوكوينس',
   'ex_en':'His eloquence moved the crowd.','ex_ar':'بلاغته حرّكت الجمهور.','ex_tr':'هيز إلوكوينس موفد ذا كراود.',
   'syn':'fluency, articulacy','ant':'clumsiness, inarticulacy','fam':'eloquent, eloquently','coll':'speak with eloquence','tip':'Eloquence is clear, persuasive speech.','mistake':'Confusing it with "elegance."'}),
('english-mastery','English Mastery',ADV,
  {'en':'Connotation','ipa':'/ˌkɒnəˈteɪʃən/','ar':'المعنى الضمني','translit':'كونوه تيهيشِن',
   'ex_en':'"Childlike" has a warm connotation.','ex_ar':'كلمة "childlike" تحمل معنى دافئًا.','ex_tr':'تشايلدايك هاز ا وورم كونوه تيهيشِن.',
   'syn':'association, implication','ant':'denotation','fam':'connote, connotative','coll':'positive connotation, negative connotation','tip':'Connotation is the feeling a word carries.','mistake':'Mixing up connotation with definition.'}),
('english-mastery','English Mastery',ADV,
  {'en':'Pragmatics','ipa':'/præɡˈmætɪks/','ar':'استعمال اللغة في السياق','translit':'براكماتيكس',
   'ex_en':'Pragmatics explains polite tone.','ex_ar':'البراغماتيك يفسّر نبرة التهذيب.','ex_tr':'براكماتيكس إكسبلينز بولايت تون.',
   'syn':'language use','ant':'grammar, syntax','fam':'pragmatic, pragmatics','coll':'study pragmatics, pragmatic meaning','tip':'Pragmatics is meaning in real context.','mistake':'Thinking it only means "practical."'}),
('fluency-journey','Fluency Journey',ADV,
  {'en':'Immersion','ipa':'/ɪˈmɜːrʒən/','ar':'انغماس (في اللغة)','translit':'إمرجن',
   'ex_en':'Immersion speeds up learning.','ex_ar':'الانغماس يسرّع التعلّم.','ex_tr':'إمرجن سبيتس آب ليرنينق.',
   'syn':'soaking, diving in','ant':'avoidance','fam':'immerse, immersed','coll':'language immersion, full immersion','tip':'Immersion means living the language daily.','mistake':'Waiting to be "ready" before immersion.'}),
('fluency-journey','Fluency Journey',ADV,
  {'en':'Instinct','ipa':'/ˈɪnstɪŋkt/','ar':'حدس، غريزة','translit':'إنستينكت',
   'ex_en':'Trust your instinct when speaking.','ex_ar':'ثق بحدسك عند التحدث.','ex_tr':'تراست يور إنستينكت وين سبيكنق.',
   'syn':'intuition, gut feeling','ant':'reasoning, planning','fam':'instinct, instinctive','coll':'trust your instinct, by instinct','tip':'Instinct is knowing without thinking.','mistake':'Overthinking and freezing mid-sentence.'}),
('fluency-journey','Fluency Journey',ADV,
  {'en':'Converse','ipa':'/kənˈvɜːrs/','ar':'يتحدث، يتبادل الحديث','translit':'كونفِرس',
   'ex_en':'Let\'s converse in English.','ex_ar':'لنتحدث بالإنجليزية.','ex_tr':'ليتس كونفِرس إن إنجلش.',
   'syn':'talk, chat','ant':'stay silent','fam':'converse, conversation','coll':'converse with, converse in','tip':'To converse is to talk with someone.','mistake':'Saying "converse with to" instead of "converse with."'}),
('fluency-journey','Fluency Journey',ADV,
  {'en':'Proficiency','ipa':'/prəˈfɪʃənsi/','ar':'إتقان، كفاءة','translit':'بروفينسي',
   'ex_en':'Test your English proficiency.','ex_ar':'اختبر إتقانك للإنجليزية.','ex_tr':'تيست يور إنجلش بروفينسي.',
   'syn':'skill, competence','ant':'incompetence','fam':'proficient, proficiency','coll':'language proficiency, high proficiency','tip':'Proficiency is your skill level.','mistake':'Confusing proficiency with perfection.'}),
('fluency-journey','Fluency Journey',ADV,
  {'en':'Tongue-tied','ipa':'/ˈtʌŋ taɪd/','ar':'عاجز عن الكلام (خجلًا)','translit':'تَنق تايد',
   'ex_en':'I got tongue-tied in the interview.','ex_ar':'صِرت عاجزًا عن الكلام في المقابلة.','ex_tr':'اي قوت تَنق تايد إن ذا إنترفيو.',
   'syn':'speechless, flustered','ant':'fluent, articulate','fam':'tongue, tie','coll':'feel tongue-tied, get tongue-tied','tip':'It means you cannot speak from nerves.','mistake':'Staying silent instead of pushing through.'}),
('saudi-greetings','Saudi Greetings',B1,
  {'en':'Hello','ipa':'/həˈloʊ/','ar':'مرحبًا','translit':'هَلو',
   'ex_en':'Hello, how are you?','ex_ar':'مرحبًا، كيف حالك؟','ex_tr':'هَلو، هاو آر يو؟',
   'syn':'hi, greetings','ant':'goodbye','fam':'hello','coll':'say hello, hello there','tip':'"Hello" works any time of day.','mistake':'Forgetting to greet before a request.'}),
('saudi-greetings','Saudi Greetings',B1,
  {'en':'Goodbye','ipa':'/ˌɡʊdˈbaɪ/','ar':'مع السلامة، وداعًا','translit':'قودباي',
   'ex_en':'Goodbye, see you tomorrow.','ex_ar':'مع السلامة، أراك غدًا.','ex_tr':'قودباي، سي يو تومورو.',
   'syn':'bye, farewell','ant':'hello, hi','fam':'goodbye','coll':'say goodbye, wave goodbye','tip':'"Goodbye" ends a meeting politely.','mistake':'Leaving without saying goodbye.'}),
('saudi-greetings','Saudi Greetings',B1,
  {'en':'Welcome','ipa':'/ˈwɛlkəm/','ar':'أهلًا وسهلًا','translit':'وِلكَم',
   'ex_en':'Welcome to our home.','ex_ar':'أهلًا وسهلًا في بيتنا.','ex_tr':'وِلكَم تو أور هوم.',
   'syn':'greetings, come in','ant':'goodbye','fam':'welcome, welcomed','coll':'welcome to, you are welcome','tip':'"Welcome" greets someone who arrives.','mistake':'Saying "welcome" instead of "you are welcome" for thanks.'}),
('saudi-greetings','Saudi Greetings',B1,
  {'en':'Good morning','ipa':'/ɡʊd ˈmɔːrnɪŋ/','ar':'صباح الخير','translit':'قود مورنينق',
   'ex_en':'Good morning, everyone.','ex_ar':'صباح الخير جميعًا.','ex_tr':'قود مورنينق، إفريوان.',
   'syn':'morning greeting','ant':'good night','fam':'morning','coll':'say good morning, good morning to you','tip':'Use it before noon.','mistake':'Saying "good morning" in the evening.'}),
('saudi-greetings','Saudi Greetings',B1,
  {'en':'Thank you','ipa':'/θæŋk juː/','ar':'شكرًا لك','translit':'ثانك يو',
   'ex_en':'Thank you for your help.','ex_ar':'شكرًا لك على مساعدتك.','ex_tr':'ثانك يو فور يور هيلب.',
   'syn':'thanks, much obliged','ant':'','fam':'thank, thanks','coll':'say thank you, thank you so much','tip':'"Thank you" shows gratitude.','mistake':'Forgetting to thank someone who helped.'}),
('saudi-conversations','Saudi Conversations',I1,
  {'en':'Invitation','ipa':'/ˌɪnvɪˈteɪʃən/','ar':'دعوة','translit':'إنفيتيهيشِن',
   'ex_en':'Thank you for the invitation.','ex_ar':'شكرًا على الدعوة.','ex_tr':'ثانك يو فور ذا إنفيتيهيشِن.',
   'syn':'invite, summons','ant':'rejection','fam':'invite, invited','coll':'accept an invitation, send an invitation','tip':'An invitation asks someone to come.','mistake':'Forgetting to RSVP to an invitation.'}),
('saudi-conversations','Saudi Conversations',I1,
  {'en':'Host','ipa':'/hoʊst/','ar':'مضيف','translit':'هوست',
   'ex_en':'Our host welcomed everyone.','ex_ar':'مضيفنا رحّب بالجميع.','ex_tr':'أور هوست وِلكَمد إفريوان.',
   'syn':'host, entertainer','ant':'guest','fam':'host, hosted','coll':'play host, host a gathering','tip':'The host receives the guests.','mistake':'Confusing host (person) with host (a lot).'}),
('saudi-conversations','Saudi Conversations',I1,
  {'en':'Guest','ipa':'/ɡɛst/','ar':'ضيف','translit':'گست',
   'ex_en':'We have guests tonight.','ex_ar':'عندنا ضيوف الليلة.','ex_tr':'وي هاف گستس تونايت.',
   'syn':'visitor','ant':'host','fam':'guest, guests','coll':'welcome a guest, house guest','tip':'A guest is someone you invited.','mistake':'Confusing "guest" with "quest."'}),
('saudi-conversations','Saudi Conversations',I1,
  {'en':'Gathering','ipa':'/ˈɡæðərɪŋ/','ar':'تجمع، مجلس','translit':'گاذرينق',
   'ex_en':'The family gathering was lovely.','ex_ar':'كان تجمع العائلة لطيفًا.','ex_tr':'ذا فاميلي گاذرينق واز لافلي.',
   'syn':'meetup, assembly','ant':'dispersal','fam':'gather, gathering','coll':'family gathering, social gathering','tip':'A gathering is people meeting together.','mistake':'Calling every gathering a "party."'}),
('saudi-conversations','Saudi Conversations',I1,
  {'en':'Hospitality','ipa':'/ˌhɒspɪˈtæləti/','ar':'كرم الضيافة','translit':'هوسبيتاليتي',
   'ex_en':'Saudi hospitality is famous.','ex_ar':'كرم الضيافة السعودي معروف.','ex_tr':'ساودي هوسبيتاليتي إز فيمس.',
   'syn':'welcome, generosity','ant':'coldness','fam':'hospitable, hospitality','coll':'show hospitality, generous hospitality','tip':'Hospitality is warm welcoming of guests.','mistake':'Confusing it with "hospital."'}),
]
