-- Migration 202609130002: Add Arabic to remaining 30 choose + 126 order exercises
-- No hamza, no em dashes. Saudi dialect.

UPDATE lesson_exercises SET payload = jsonb_set(payload, '{question,ar}', to_jsonb('مش كبير يعني:'::text)) WHERE id = 763;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{question,ar}', to_jsonb('احتاج ___ ساعة عشان اخلص.'::text)) WHERE id = 698;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{question,ar}', to_jsonb('كنت جوعان، ___ سويت ساندويتش.'::text)) WHERE id = 727;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{question,ar}', to_jsonb('___ هو صغير، يدير الفريق.'::text)) WHERE id = 730;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{question,ar}', to_jsonb('اي واحد مكتوب صح؟'::text)) WHERE id = 688;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{question,ar}', to_jsonb('اختار الجملة المكتوبة صح:'::text)) WHERE id = 686;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{question,ar}', to_jsonb('__ اخوانك بالبيت؟'::text)) WHERE id = 691;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{question,ar}', to_jsonb('اكثر طلب مهذب:'::text)) WHERE id = 762;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{question,ar}', to_jsonb('احد يسالك هل تحب السمك؟ تحبه:'::text)) WHERE id = 770;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{question,ar}', to_jsonb('خفف الرفض باسلوب مهذب:'::text)) WHERE id = 734;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{question,ar}', to_jsonb('هو ___ يجري.'::text)) WHERE id = 774;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{question,ar}', to_jsonb('اي طلب اكثر لطف؟'::text)) WHERE id = 639;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{question,ar}', to_jsonb('علي نسي ___ مفاتيح.'::text)) WHERE id = 702;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{question,ar}', to_jsonb('انا ___ ما اكلت سوشي.'::text)) WHERE id = 784;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{question,ar}', to_jsonb('الاجتماع ___ الاثنين.'::text)) WHERE id = 670;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{question,ar}', to_jsonb('___ تتعلم انجليزي؟ عشان الشغل:'::text)) WHERE id = 752;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{question,ar}', to_jsonb('___ جوالي؟ تسال عن المكان:'::text)) WHERE id = 749;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{question,ar}', to_jsonb('احد يقول كيف حالك؟ تجاوب:'::text)) WHERE id = 705;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{question,ar}', to_jsonb('ما عندي ___.'::text)) WHERE id = 779;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{question,ar}', to_jsonb('اي كلمة معناها قبعة؟'::text)) WHERE id = 674;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{question,ar}', to_jsonb('اي كلمة تبدأ بصوت th في كلمة think؟'::text)) WHERE id = 680;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{question,ar}', to_jsonb('جمع كلمة bus:'::text)) WHERE id = 683;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{question,ar}', to_jsonb('Hop مع حرف e الصامت تصير:'::text)) WHERE id = 681;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{question,ar}', to_jsonb('رتب علامات القصة:'::text)) WHERE id = 736;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{question,ar}', to_jsonb('___ الجزمة هناك تبعي.'::text)) WHERE id = 694;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{question,ar}', to_jsonb('اي رقم هو 15؟'::text)) WHERE id = 712;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{question,ar}', to_jsonb('9:30 بالانجليزي:'::text)) WHERE id = 715;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{question,ar}', to_jsonb('اسال عن رغبة بادب:'::text)) WHERE id = 724;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{question,ar}', to_jsonb('تطلع جواز سفرك عند:'::text)) WHERE id = 747;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{question,ar}', to_jsonb('اسال عن تحديث الحالة:'::text)) WHERE id = 739;

UPDATE lesson_exercises SET payload = jsonb_set(payload, '{prompt,ar}', to_jsonb('رتب: كتاب.'::text)) WHERE id = 1456;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{prompt,ar}', to_jsonb('رتب: انا طالب.'::text)) WHERE id = 1453;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{prompt,ar}', to_jsonb('رتب: هي اختي.'::text)) WHERE id = 1459;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{prompt,ar}', to_jsonb('رتب: كتابين.'::text)) WHERE id = 1465;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{prompt,ar}', to_jsonb('رتب: هذا قلمي.'::text)) WHERE id = 1462;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{prompt,ar}', to_jsonb('رتب: متى الاجتماع؟'::text)) WHERE id = 1390;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{prompt,ar}', to_jsonb('رتب: وين البنك؟'::text)) WHERE id = 1387;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{prompt,ar}', to_jsonb('رتب: كيف حالك؟'::text)) WHERE id = 1393;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{prompt,ar}', to_jsonb('رتب: ليش تأخرت؟'::text)) WHERE id = 1396;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{prompt,ar}', to_jsonb('رتب: هلو، كيف حالك؟'::text)) WHERE id = 1302;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{prompt,ar}', to_jsonb('رتب: كيف حالك اليوم؟'::text)) WHERE id = 1311;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{prompt,ar}', to_jsonb('رتب: وش اسمك؟'::text)) WHERE id = 1308;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{prompt,ar}', to_jsonb('رتب: لو سمحت، بليز.'::text)) WHERE id = 1314;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{prompt,ar}', to_jsonb('رتب: اسف، تأخرت.'::text)) WHERE id = 1305;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{prompt,ar}', to_jsonb('رتب: A حرف apple.'::text)) WHERE id = 1438;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{prompt,ar}', to_jsonb('رتب: الجبن حلو.'::text)) WHERE id = 1447;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{prompt,ar}', to_jsonb('رتب: اكتب اسمك.'::text)) WHERE id = 1450;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{prompt,ar}', to_jsonb('رتب: هذا حلو.'::text)) WHERE id = 1444;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{prompt,ar}', to_jsonb('رتب: A E I O U.'::text)) WHERE id = 1441;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{prompt,ar}', to_jsonb('رتب: اقدر اسبح.'::text)) WHERE id = 1414;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{prompt,ar}', to_jsonb('رتب: تفضل.'::text)) WHERE id = 1423;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{prompt,ar}', to_jsonb('رتب: ممكن ادخل؟'::text)) WHERE id = 1420;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{prompt,ar}', to_jsonb('رتب: ممكن تساعدني؟'::text)) WHERE id = 1417;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{prompt,ar}', to_jsonb('رتب: بالليل ارتاح.'::text)) WHERE id = 1480;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{prompt,ar}', to_jsonb('رتب: هي تشرب قهوة.'::text)) WHERE id = 1471;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{prompt,ar}', to_jsonb('رتب: اروح الشغل الساعة ثمان.'::text)) WHERE id = 1474;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{prompt,ar}', to_jsonb('رتب: انام الساعة عشر.'::text)) WHERE id = 1477;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{prompt,ar}', to_jsonb('رتب: اصحى الساعة ست.'::text)) WHERE id = 1468;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{prompt,ar}', to_jsonb('رتب: ابوي مدرس.'::text)) WHERE id = 1330;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{prompt,ar}', to_jsonb('رتب: عندي سيارة.'::text)) WHERE id = 1318;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{prompt,ar}', to_jsonb('رتب: لازم اروح.'::text)) WHERE id = 1333;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{prompt,ar}', to_jsonb('رتب: هذا كتابي.'::text)) WHERE id = 1321;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{prompt,ar}', to_jsonb('رتب: فيه مشكلة.'::text)) WHERE id = 1324;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{prompt,ar}', to_jsonb('رتب: قلم مين هذا؟'::text)) WHERE id = 1327;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{prompt,ar}', to_jsonb('رتب: روح طول.'::text)) WHERE id = 1432;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{prompt,ar}', to_jsonb('رتب: ساكن بجدة.'::text)) WHERE id = 1426;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{prompt,ar}', to_jsonb('رتب: اشتغل بالصبح.'::text)) WHERE id = 1429;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{prompt,ar}', to_jsonb('رتب: اروح المدرسة.'::text)) WHERE id = 1435;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{prompt,ar}', to_jsonb('رتب: اليوم الاثنين.'::text)) WHERE id = 1405;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{prompt,ar}', to_jsonb('رتب: كم سعره؟'::text)) WHERE id = 1411;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{prompt,ar}', to_jsonb('رتب: المدرسة تبدأ سبتمبر.'::text)) WHERE id = 1408;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{prompt,ar}', to_jsonb('رتب: ثلاثة كتب.'::text)) WHERE id = 1399;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{prompt,ar}', to_jsonb('رتب: الساعة ثلاثة.'::text)) WHERE id = 1402;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{prompt,ar}', to_jsonb('رتب: اهلي ساكنين بجدة.'::text)) WHERE id = 1483;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{prompt,ar}', to_jsonb('رتب: هي حزينة.'::text)) WHERE id = 1495;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{prompt,ar}', to_jsonb('رتب: اشرب ماي.'::text)) WHERE id = 1489;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{prompt,ar}', to_jsonb('رتب: سكر الباب.'::text)) WHERE id = 1492;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{prompt,ar}', to_jsonb('رتب: مديري طيب.'::text)) WHERE id = 1486;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{prompt,ar}', to_jsonb('رتب: بادررس.'::text)) WHERE id = 1351;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{prompt,ar}', to_jsonb('رتب: بادررس طب.'::text)) WHERE id = 1363;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{prompt,ar}', to_jsonb('رتب: بتساعدني؟'::text)) WHERE id = 1366;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{prompt,ar}', to_jsonb('رتب: بأسافر بكرا.'::text)) WHERE id = 1360;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{prompt,ar}', to_jsonb('رتب: بساعدك.'::text)) WHERE id = 1354;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{prompt,ar}', to_jsonb('رتب: اظن بتطول.'::text)) WHERE id = 1357;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{prompt,ar}', to_jsonb('رتب: رحت مكة.'::text)) WHERE id = 1342;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{prompt,ar}', to_jsonb('رتب: ما رحت.'::text)) WHERE id = 1348;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{prompt,ar}', to_jsonb('رتب: رحت؟'::text)) WHERE id = 1345;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{prompt,ar}', to_jsonb('رتب: هي اشتغلت امبارح.'::text)) WHERE id = 1339;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{prompt,ar}', to_jsonb('رتب: كنت بالبيت.'::text)) WHERE id = 1336;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{prompt,ar}', to_jsonb('رتب بالانجليزي:'::text)) WHERE id = 766;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{prompt,ar}', to_jsonb('رتب بالانجليزي:'::text)) WHERE id = 764;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{prompt,ar}', to_jsonb('رتب: اعطني القلم.'::text)) WHERE id = 700;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{prompt,ar}', to_jsonb('رتب: خلني اوضح النقطة.'::text)) WHERE id = 1384;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{prompt,ar}', to_jsonb('رتب: مرفق التقرير.'::text)) WHERE id = 1369;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{prompt,ar}', to_jsonb('رتب: اقترح نحسن الطريقة.'::text)) WHERE id = 1375;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{prompt,ar}', to_jsonb('رتب: ممكن تلخصها؟'::text)) WHERE id = 1372;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{prompt,ar}', to_jsonb('رتب: نقدر نتفاوض على الموعد.'::text)) WHERE id = 1378;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{prompt,ar}', to_jsonb('رتب: اليوم بصور نتايجنا.'::text)) WHERE id = 1381;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{prompt,ar}', to_jsonb('رتب بالاختصارات: احنا جاهزين.'::text)) WHERE id = 615;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{prompt,ar}', to_jsonb('رتب: هي مشغولة.'::text)) WHERE id = 608;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{prompt,ar}', to_jsonb('رتب السوال: هي بالبيت؟'::text)) WHERE id = 610;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{prompt,ar}', to_jsonb('رتب: تقدر تساعدني؟'::text)) WHERE id = 632;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{prompt,ar}', to_jsonb('رتب: ما اقدر اجي بكرا.'::text)) WHERE id = 634;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{prompt,ar}', to_jsonb('رتب: هو مو بالشغل اليوم.'::text)) WHERE id = 618;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{prompt,ar}', to_jsonb('رتب: كان مشغول امبارح؟'::text)) WHERE id = 628;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{prompt,ar}', to_jsonb('رتب بالانجليزي:'::text)) WHERE id = 788;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{prompt,ar}', to_jsonb('رتب: طلعنا لان وقت متأخر.'::text)) WHERE id = 728;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{prompt,ar}', to_jsonb('رتب: تحب قهوة؟'::text)) WHERE id = 649;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{prompt,ar}', to_jsonb('رتب: ما نشتغل الجمعة.'::text)) WHERE id = 647;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{prompt,ar}', to_jsonb('رتب: بنام بدري.'::text)) WHERE id = 658;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{prompt,ar}', to_jsonb('رتب: عندهم بيت كبير.'::text)) WHERE id = 653;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{prompt,ar}', to_jsonb('رتب: لازم تتصل عليه.'::text)) WHERE id = 657;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{prompt,ar}', to_jsonb('رتب: الجو حار اليوم.'::text)) WHERE id = 603;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{prompt,ar}', to_jsonb('رتب بالانجليزي:'::text)) WHERE id = 783;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{prompt,ar}', to_jsonb('رتب: انا جاهز.'::text)) WHERE id = 595;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{prompt,ar}', to_jsonb('رتب بالانجليزي:'::text)) WHERE id = 757;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{prompt,ar}', to_jsonb('رتب بالانجليزي:'::text)) WHERE id = 760;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{prompt,ar}', to_jsonb('رتب بالانجليزي:'::text)) WHERE id = 771;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{prompt,ar}', to_jsonb('رتب: اظن فكرة حلوة.'::text)) WHERE id = 732;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{prompt,ar}', to_jsonb('رتب بالانجليزي:'::text)) WHERE id = 773;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{prompt,ar}', to_jsonb('رتب: ممكن اخذ رسالة؟'::text)) WHERE id = 740;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{prompt,ar}', to_jsonb('رتب باسلوب مهذب: ممكن تفتح الباب؟'::text)) WHERE id = 637;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{prompt,ar}', to_jsonb('رتب: هذا كتابها.'::text)) WHERE id = 701;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{prompt,ar}', to_jsonb('رتب بالانجليزي:'::text)) WHERE id = 785;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{prompt,ar}', to_jsonb('رتب: هو عند البنك.'::text)) WHERE id = 664;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{prompt,ar}', to_jsonb('رتب: كتابك على المكتب.'::text)) WHERE id = 667;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{prompt,ar}', to_jsonb('رتب: الكرة تحت السرير.'::text)) WHERE id = 668;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{prompt,ar}', to_jsonb('رتب: هي تروح المدرسة.'::text)) WHERE id = 644;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{prompt,ar}', to_jsonb('رتب: اروح الشغل كل يوم.'::text)) WHERE id = 640;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{prompt,ar}', to_jsonb('رتب بالانجليزي:'::text)) WHERE id = 755;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{prompt,ar}', to_jsonb('رتب بالانجليزي:'::text)) WHERE id = 753;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{prompt,ar}', to_jsonb('رتب بالانجليزي:'::text)) WHERE id = 748;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{prompt,ar}', to_jsonb('رتب بالانجليزي:'::text)) WHERE id = 750;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{prompt,ar}', to_jsonb('رتب: صباح الخير.'::text)) WHERE id = 703;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{prompt,ar}', to_jsonb('رتب: اسمي سارة.'::text)) WHERE id = 708;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{prompt,ar}', to_jsonb('رتب: مشكور وايد.'::text)) WHERE id = 706;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{prompt,ar}', to_jsonb('رتب بالانجليزي:'::text)) WHERE id = 780;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{prompt,ar}', to_jsonb('رتب: الاسبوع اللي راح رحت جدة.'::text)) WHERE id = 735;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{prompt,ar}', to_jsonb('رتب: فيه كرسيين.'::text)) WHERE id = 697;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{prompt,ar}', to_jsonb('رتب: هذي كتبي.'::text)) WHERE id = 695;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{prompt,ar}', to_jsonb('رتب: نلتقي الاثنين.'::text)) WHERE id = 713;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{prompt,ar}', to_jsonb('رتب: الساعة سبعة.'::text)) WHERE id = 716;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{prompt,ar}', to_jsonb('رتب: اشرب ماي.'::text)) WHERE id = 718;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{prompt,ar}', to_jsonb('رتب: اروح البيت الحين.'::text)) WHERE id = 720;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{prompt,ar}', to_jsonb('رتب: اتصل علي بعدين.'::text)) WHERE id = 725;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{prompt,ar}', to_jsonb('رتب: ابغى شاي، بليز.'::text)) WHERE id = 722;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{prompt,ar}', to_jsonb('رتب: هذي امي.'::text)) WHERE id = 742;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{prompt,ar}', to_jsonb('رتب: شاي واحد، بليز.'::text)) WHERE id = 744;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{prompt,ar}', to_jsonb('رتب: ابعتلي التقرير.'::text)) WHERE id = 746;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{prompt,ar}', to_jsonb('رتب: تأخروا.'::text)) WHERE id = 622;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{prompt,ar}', to_jsonb('رتب السوال: كنت بالبيت؟'::text)) WHERE id = 624;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{prompt,ar}', to_jsonb('رتب: تأخروا.'::text)) WHERE id = 604;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{prompt,ar}', to_jsonb('رتب بالانجليزي:'::text)) WHERE id = 768;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{prompt,ar}', to_jsonb('رتب: بساعدك.'::text)) WHERE id = 661;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{prompt,ar}', to_jsonb('رتب: خلنا نبدأ.'::text)) WHERE id = 737;
UPDATE lesson_exercises SET payload = jsonb_set(payload, '{prompt,ar}', to_jsonb('رتب السوال: انت جاهز؟'::text)) WHERE id = 598;
